FROM python:3.10-slim



WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY shop.py /app

EXPOSE 8000

CMD ["uvicorn", "shop:app","--host","0.0.0.0", "--port","8000","--proxy-headers"]



