FROM python:3.10-slim


WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY order.py /app

EXPOSE 8000

CMD ["uvicorn", "order:app","--host","0.0.0.0", "--port","8000","--reload"]



